export const filterTypes = [
  {id: 1, type: 'Site Status'},
  {id: 2, type: 'Country'},
  {id: 3, type: 'Site Type'},
  {id: 4, type: 'Site Subtype'},
  {id: 5, type: 'Vendor'},
];

export const filterCategories = [
  {
    id: 1,
    name: 'Select All',
    type: 'Site Status',
  },
  {id: 2, name: 'Active', type: 'Site Status'},
  {id: 3, name: 'Inactive', type: 'Site Status'},
  {id: 4, name: 'USA', type: 'Country'},
  {id: 5, name: 'RoW', type: 'Country'},
  {id: 6, name: 'Select All', type: 'Site Type'},
  {id: 7, name: 'Data Center', type: 'Site Type'},
  {id: 8, name: 'Office', type: 'Site Type'},
  {id: 9, name: 'Branch', type: 'Site Type'},
  {id: 10, name: 'ATM', type: 'Site Type'},
  {id: 11, name: '3rd Party', type: 'Site Type'},
  {id: 12, name: 'Other', type: 'Site Type'},
  {id: 13, name: 'Select All', type: 'Site Subtype'},
  {id: 14, name: 'DC - Core', type: 'Site Subtype'},
  {id: 15, name: 'DC - FAMC', type: 'Site Subtype'},
  {id: 16, name: 'DC - Equinix', type: 'Site Subtype'},
  {id: 17, name: 'Data Center', type: 'Site Subtype'},
  {id: 18, name: 'Contanct Center', type: 'Site Subtype'},
  {id: 19, name: 'Loan Office', type: 'Site Subtype'},
  {id: 20, name: 'Office - Large', type: 'Site Subtype'},
  {id: 21, name: 'Office - Medium', type: 'Site Subtype'},
  {id: 22, name: 'Office - Small', type: 'Site Subtype'},
  {id: 23, name: 'Trading Floor', type: 'Site Subtype'},
  {id: 24, name: 'Branch', type: 'Site Subtype'},
  {id: 25, name: 'InvestorsBank', type: 'Site Subtype'},
  {id: 26, name: 'HSBC', type: 'Site Subtype'},
  {id: 27, name: 'ATM-Branded', type: 'Site Subtype'},
  {id: 28, name: 'ATM-Owned', type: 'Site Subtype'},
  {id: 29, name: '3rd Party', type: 'Site Subtype'},
  {id: 30, name: 'Other', type: 'Site Subtype'},
  {id: 31, name: 'Select all', type: 'Vendor'},
  {id: 32, name: 'AT&T', type: 'Vendor'},
  {id: 33, name: 'AT&T Mobility', type: 'Vendor'},
  {id: 34, name: 'AT&T OneNet', type: 'Vendor'},
  {id: 35, name: 'Centurylink', type: 'Vendor'},
  {id: 36, name: 'Comcast', type: 'Vendor'},
  {id: 37, name: 'Consolidated Comms', type: 'Vendor'},
  {id: 38, name: 'Cox', type: 'Vendor'},
  {id: 39, name: 'Crown Castle', type: 'Vendor'},
  {id: 40, name: 'DirecTV', type: 'Vendor'},
  {id: 41, name: 'Frontier', type: 'Vendor'},
  {id: 42, name: 'Granite', type: 'Vendor'},
  {id: 43, name: 'Optimum', type: 'Vendor'},
  {id: 44, name: 'Spectrum', type: 'Vendor'},
  {id: 45, name: 'TDS Telecom', type: 'Vendor'},
  {id: 46, name: 'Verizon', type: 'Vendor'},
  {id: 47, name: 'Verizon Wireless', type: 'Vendor'},
  {id: 48, name: 'VTel', type: 'Vendor'},
  {id: 49, name: 'Windstream', type: 'Vendor'},
];
